# Generated by Django 5.2.7 on 2025-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
