# Generated by Django 5.2.7 on 2025-10-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsNewsApp', '0002_alter_comment_text_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
